x

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -53,14 +53,20 @@ jobs:
           java-version: '17'
 
       - name: Run tests and check Jacoco coverage
+        id: coverage_check  # Add an ID to the step
         run: |
           mvn clean verify
           COVERAGE=$(mvn jacoco:report | grep "overall:" | awk '{print $2}' | tr -d "%,")
           echo "Code coverage: $COVERAGE%"
-          if (( $(echo "$COVERAGE <99" | bc -l) )); then
-            echo "Code coverage is below 60%. Failing the build."
-            exit 1
+          echo "::set-output name=coverage::$COVERAGE" # Set the coverage as an output variable
+          if (( $(echo "$COVERAGE < 99" | bc -l) )); then # Example: 99% threshold
+            echo "Code coverage is below 99%. Failing the build."
+            exit 1 # Fail the step if coverage is below threshold
           fi
+
+      - name: Fail workflow if coverage is insufficient
+        if: steps.coverage_check.outcome == 'failure' # Check the outcome of the previous step
+        run: exit 1
 
   sonarqube:
     runs-on: ubuntu-latest
